

CREATE TABLE COMTECOPSEQ (
  TABLE_NAME varchar(20) ,
  NEXT_ID int
);


CREATE TABLE COMTNLOGINLOG (
  LOG_ID char(20) NOT NULL ,
  CONECT_ID varchar(20) DEFAULT NULL,
  CONECT_IP varchar(23) DEFAULT NULL,
  CONECT_MTHD char(4) DEFAULT NULL,
  ERROR_OCCRRNC_AT char(1) DEFAULT NULL,
  ERROR_CODE char(3) DEFAULT NULL ,
  CREAT_DT datetime DEFAULT getdate() ,
  PRIMARY KEY (LOG_ID)
) ;


CREATE TABLE COMTNSYSLOG (
  REQUST_ID char(20) NOT NULL,
  JOB_SE_CODE char(3) DEFAULT NULL,
  OCCRRNC_DE char(8) DEFAULT NULL,
  SRVC_NM varchar(200) DEFAULT NULL,
  METHOD_NM varchar(200) DEFAULT NULL,
  PROCESS_SE_CODE char(3) DEFAULT NULL,
  PROCESS_CO int(11) DEFAULT NULL,
  PROCESS_TIME varchar(10) DEFAULT NULL,
  ERROR_SE char(1) DEFAULT NULL,
  ERROR_CODE char(3) DEFAULT NULL,
  ERROR_CO int(11) DEFAULT NULL,
  RSPNS_CODE char(3) DEFAULT NULL,
  INSTT_CODE char(7) DEFAULT NULL,
  TRGET_MENU_NM varchar(200) DEFAULT NULL,
  RQESTER_IP varchar(128) DEFAULT NULL,
  RQESTER_ID varchar(20) DEFAULT NULL,
  SQLID varchar(100) DEFAULT NULL,
  SQL_PARAM text DEFAULT NULL,
  SQL_QUERY text DEFAULT NULL,
  METHOD_RESULT text DEFAULT NULL,
  OCCRRNC_DATE datetime DEFAULT getdate(),
  PRIMARY KEY (REQUST_ID)
) ;

CREATE TABLE IDS (
  TABLE_NAME varchar(20) NOT NULL DEFAULT '',
  NEXT_ID int(11) NOT NULL DEFAULT 0
) ;


CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(60) DEFAULT NULL,
  CL_CODE_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM datetime DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM datetime DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL
) ;


CREATE TABLE LETTCCMMNCODE (
  CODE_ID varchar(20) NOT NULL,
  CODE_ID_NM varchar(60) DEFAULT NULL,
  CODE_ID_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  CL_CODE char(3) DEFAULT NULL,
  FRST_REGIST_PNTTM datetime DEFAULT getdate(),
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM datetime ,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID)
) ;

CREATE TABLE LETTCCMMNDETAILCODE (
  CODE_ID varchar(20) NOT NULL,
  CODE varchar(20) NOT NULL,
  CODE_NM varchar(60) DEFAULT NULL,
  CODE_DC varchar(200) DEFAULT NULL,
  CODE_ETC1 varchar(200) DEFAULT NULL,
  CODE_ETC2 varchar(200) DEFAULT NULL,
  CODE_ETC3 varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM datetime DEFAULT getdate(),
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM datetime ,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CODE)
) ;


CREATE TABLE LETTNAUTHORINFO (
  AUTHOR_CODE varchar(30) NOT NULL,
  AUTHOR_NM varchar(60) NOT NULL,
  AUTHOR_DC varchar(200) DEFAULT NULL,
  AUTHOR_CREAT_DE char(20) NOT NULL
) ;


CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_STRE_COURS varchar(2000) NOT NULL,
  STRE_FILE_NM varchar(255) NOT NULL,
  ORIGNL_FILE_NM varchar(255) DEFAULT NULL,
  FILE_EXTSN varchar(20) NOT NULL,
  FILE_SIZE int(11) DEFAULT NULL,
  CON_SEQ int(11) DEFAULT 0,
  FILE_ORDER int(11) DEFAULT 0,
  DETAIL_SEQ varchar(10) DEFAULT NULL,
  FILE_THUMNAIL varchar(40) DEFAULT NULL,
  PLAY_TIME varchar(20) DEFAULT NULL,
  FILE_WIDTH varchar(10) DEFAULT NULL,
  FILE_HEIGHT varchar(20) DEFAULT NULL,
  USEYN char(1) DEFAULT 'N',
  PRIMARY KEY (ATCH_FILE_ID)
) ;


CREATE TABLE RTETCCODE (
  CODE_ID varchar(20) DEFAULT NULL,
  CODE_NM varchar(200) DEFAULT NULL
) ;



CREATE TABLE RTETNAUTH (
  MNGR_SE varchar(20) DEFAULT NULL,
  URL varchar(200) DEFAULT NULL
) ;


CREATE TABLE TB_ADMIN (
  ADMIN_ID varchar(20) NOT NULL,
  ADMIN_NAME varchar(30) DEFAULT NULL,
  ADMIN_PASSWORD varchar(255) NOT NULL,
  EMP_NO varchar(10) DEFAULT NULL,
  DEPT_ID varchar(20) DEFAULT NULL,
  DEPT_NAME varchar(30) DEFAULT NULL,
  ADMIN_EMAIL varchar(250) DEFAULT NULL,
  ADMIN_TEL varchar(15) DEFAULT NULL,
  REG_DATE datetime DEFAULT getdate(),
  UPDATE_PASSWORD datetime DEFAULT NULL,
  ADMIN_LEVEL varchar(15) DEFAULT NULL,
  LOCK_YN char(1) DEFAULT NULL,
  USE_YN char(1) DEFAULT NULL,
  PRIMARY KEY (ADMIN_ID)
) ;



CREATE TABLE TB_ATTENDANCE (
  RES_SEQ int(11) NOT NULL,
  ATT_SEQ int(11) NOT NULL,
  USER_ID varchar(20) DEFAULT NULL,
  RES_DAY char(8) DEFAULT NULL,
  ROOM_INTIME char(5) DEFAULT NULL,
  ROOM_OTTIME char(5) DEFAULT NULL,
  NOTIN_TIME char(5) DEFAULT NULL,
  NOTOT_TIME char(5) DEFAULT NULL,
  ATT_REGDATE datetime DEFAULT NULL,
  ATT_UPDATE datetime DEFAULT NULL,
  LOGIN datetime DEFAULT NULL,
  LOGOUT datetime DEFAULT NULL
) ;



CREATE TABLE TB_AVAYASENDMESSAGE (
  REQUESTID varchar(16) NOT NULL,
  REQ_MESSAGE varchar(50) NOT NULL,
  REQ_MESSAGE_TXT text DEFAULT NULL,
  RES_MESSAGE varchar(50) DEFAULT NULL,
  RES_MESSAGE_TXT text DEFAULT NULL,
  REQ_REGDATE datetime NOT NULL DEFAULT getdate()
) ;


CREATE TABLE TB_BOARD (
  BOARD_SEQ int(11) NOT NULL  primary key IDENTITY(1,1),
  BOARD_TITLE varchar(120) DEFAULT NULL,
  BOARD_NOTICE_USEYN char(1) DEFAULT 'N',
  BOARD_NOTICE_STARTDAY varchar(8) DEFAULT NULL,
  BOARD_NOTICE_ENDDAY varchar(8) DEFAULT NULL,
  BOARD_GUBUN char(3) NOT NULL,
  BOARD_CONTENT text DEFAULT NULL,
  BOARD_RETURN_CONTENT text DEFAULT NULL,
  BOARD_REGDATE datetime DEFAULT getdate(),
  BOARD_REG_ID varchar(30) DEFAULT NULL,
  BOARD_UPDATE_DATE date DEFAULT NULL,
  BOARD_UPDATE_ID varchar(30) DEFAULT NULL,
  BOARD_FILE01 varchar(255) DEFAULT NULL,
  BOARD_FILE02 varchar(255) DEFAULT NULL,
  BOARD_VIEW_YN char(1) DEFAULT 'N',
  BOARD_FAQ_GUBUN varchar(20) DEFAULT NULL,
  BOARD_VISITED int(11) DEFAULT 0,
  BOARD_TOP_SEQ varchar(10) DEFAULT NULL
);



CREATE TABLE TB_CALENDER (
  DATES char(8) DEFAULT NULL,
  YEAR char(4) DEFAULT NULL,
  MONTH char(2) DEFAULT NULL,
  DAY char(2) DEFAULT NULL
) ;



CREATE TABLE TB_CENTERINFO (
  CENTER_ID char(9) NOT NULL primary key,
  CENTER_NM varchar(30) DEFAULT NULL,
  CENTER_ZIPCODE char(7) DEFAULT NULL,
  CENTER_ADDR1 varchar(200) DEFAULT NULL,
  CENTER_ADDR2 varchar(200) DEFAULT NULL,
  CENTER_TEL varchar(15) DEFAULT NULL,
  CENTER_FAX varchar(15) DEFAULT NULL,
  CENTER_USER_ID varchar(30) DEFAULT NULL,
  CENTER_REGDATE datetime DEFAULT getdate(),
  CENTER_UPDATE_USER_ID varchar(30) DEFAULT NULL,
  CENTER_UPDATE_DATE datetime DEFAULT NULL,
  CENTER_IMG varchar(50) DEFAULT NULL,
  CENTER_URL varchar(250) DEFAULT NULL,
  CENTER_SEAT_IMG varchar(50) DEFAULT NULL,
  CENTER_USE_YN char(1) NOT NULL DEFAULT '1',
  REST_INFO varchar(1200) DEFAULT NULL,
  MEETINGROOM_INFO varchar(1200) DEFAULT NULL,
  CENTER_INFO text DEFAULT NULL,
  ADMIN_APPROVAL_YN char(1) DEFAULT '1'
) ;




CREATE TABLE TB_EMPINFO (
  EMPID varchar(20) DEFAULT NULL,
  EMPNO varchar(30) DEFAULT NULL,
  EMPNAME varchar(10) DEFAULT NULL,
  DEPTNAME varchar(30) DEFAULT NULL,
  DEPTCODE varchar(10) DEFAULT NULL,
  EMPGARD varchar(15) DEFAULT NULL,
  EMPGARDCODE varchar(20) DEFAULT NULL,
  EMPJIKW varchar(20) DEFAULT NULL,
  EMPJIKWCODE varchar(20) DEFAULT NULL,
  EMPHANDPHONE varchar(15) DEFAULT NULL,
  EMPTELPHONE varchar(15) DEFAULT NULL,
  EMPMAIL varchar(255) DEFAULT NULL,
  ADMIN_GUBUN varchar(20) DEFAULT NULL,
  UPDATE_DATE datetime NOT NULL DEFAULT getdate(),
  AVAYA_USERID varchar(30) DEFAULT NULL,
  DT_COENT varchar(8) DEFAULT NULL,
  CD_LVLGRD varchar(10) DEFAULT NULL
) ;



CREATE TABLE TB_EQUIPMENTINFO (
  EQUP_CODE char(15) NOT NULL primary key,
  EQUIPMENT_ID varchar(15) NOT NULL,
  EQUIPMENT_NAME varchar(20) NOT NULL,
  CENTER_ID varchar(15) NOT NULL,
  EQUP_SEIAL varchar(30) DEFAULT NULL,
  SWC_SEQ int(11) DEFAULT 0,
  USER_ID varchar(20) DEFAULT NULL,
  REG_DATE datetime DEFAULT NULL,
  COMPANY varchar(50) DEFAULT NULL,
  REMARK varchar(2000) DEFAULT NULL,
  EQUP_INDATE datetime NOT NULL DEFAULT getdate() ON UPDATE getdate(),
  EQUP_OTDATE datetime NULL DEFAULT NULL,
  USE_YN char(1) DEFAULT 'N',
  EQUIP_STATE varchar(30) DEFAULT NULL,
  EQUIP_IMG varchar(50) DEFAULT NULL
) ;



CREATE TABLE TB_JOBINFO (
  EMPJIKW varchar(30) DEFAULT NULL,
  EMPJIKWCODE varchar(15) DEFAULT NULL
) ;



CREATE TABLE TB_MESSAGEINFO (
  MSG_SEQ int(11) NOT NULL IDENTITY(1,1) primary key ,
  MSG_GUBUN varchar(20) NOT NULL,
  MSG_TITLE varchar(100) NOT NULL,
  MSG_SENDTYPE varchar(20) NOT NULL,
  MSG_STARTDAY char(8) DEFAULT NULL,
  MSG_ENDDAY char(8) DEFAULT NULL,
  MSG_CONTENT text DEFAULT NULL,
  MSG_REG_ID varchar(20) DEFAULT NULL,
  MSG_REG_DATE datetime DEFAULT getdate(),
  MSG_UPDATE_ID varchar(20) DEFAULT NULL,
  MSG_UPDATE_DATE datetime DEFAULT NULL,
  MSG_VARINFO varchar(100) DEFAULT NULL
) ;



CREATE TABLE TB_ORGINFO (
  DEPTCODE varchar(50) DEFAULT NULL,
  DEPTNAME varchar(50) DEFAULT NULL,
  UPDATE_DATE datetime NOT NULL DEFAULT getdate(),
  USE_YN char(1) DEFAULT 'Y'
) ;



CREATE TABLE TB_SWC_ROOM (
  SWC_SEQ int(11) NOT NULL IDENTITY(1,1) primary key ,
  SEAT_NAME varchar(80) DEFAULT NULL,
  CENTER_PARTID varchar(20) DEFAULT NULL,
  ROOM_NAME varchar(80) DEFAULT NULL,
  CENTER_ID char(9) NOT NULL,
  EQUIPMENT_STATE varchar(2000) DEFAULT NULL,
  ROOM_TYPE varchar(25) DEFAULT NULL,
  MAX_CNT int(11) DEFAULT NULL,
  SWC_USEYN char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM datetime DEFAULT getdate(),
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM datetime DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  SEAT_VIEW char(1) DEFAULT 'N',
  SEAT_ORDER int(11) DEFAULT 0,
  SEAT_IMG1 varchar(50) DEFAULT NULL,
  SEAT_IMG2 varchar(50) DEFAULT NULL,
  TERMINAL_NUMBER varchar(10) DEFAULT NULL,
  TERMINAL_ID varchar(10) DEFAULT NULL,
  TERMINAL_TEL varchar(20) DEFAULT NULL,
  AVAYA_USERID varchar(30) DEFAULT NULL,
  AVAYA_CONFI_ID varchar(30) DEFAULT NULL,
  END_NAME varchar(10) DEFAULT NULL,
  USER_EMAIL varchar(250) DEFAULT NULL,
  USER_LAST_NM varchar(50) DEFAULT NULL,
  USER_FIRST_NM varchar(50) DEFAULT NULL,
  AVAYA_ROOMCODE varchar(50) DEFAULT NULL,
  SEAT_CONFIRMGUBUN varchar(30) DEFAULT NULL,
  SEAT_EQUPGUBUN varchar(30) DEFAULT NULL,
  SEAT_ADMINID varchar(500) DEFAULT NULL
) ;



CREATE TABLE TB_SWCRESERVATION (
  RES_SEQ int(11) NOT NULL IDENTITY(1,1) primary key ,
  SWC_SEQ int(11) NOT NULL,
  CENTER_ID char(9) NOT NULL,
  RES_GUBUN varchar(30) DEFAULT NULL,
  USER_ID varchar(30) DEFAULT NULL,
  DEPT_ID varchar(30) DEFAULT NULL,
  RANK_ID varchar(30) DEFAULT NULL,
  RES_STARTDAY char(8) DEFAULT NULL,
  RES_ENDDAY char(8) DEFAULT NULL,
  RES_STARTTIME char(4) DEFAULT NULL,
  RES_ENDTIME char(4) DEFAULT NULL,
  REG_DATE datetime DEFAULT getdate(),
  RESERV_PROCESS_GUBUN varchar(30) DEFAULT NULL,
  RESERVATION_REASON varchar(1000) DEFAULT NULL,
  CANCEL_REASON varchar(1000) DEFAULT NULL,
  CANCEL_CODE varchar(30) DEFAULT NULL,
  RES_REMARK varchar(1000) DEFAULT NULL,
  PROXY_YN char(1) DEFAULT NULL,
  PROXY_USER_ID varchar(30) DEFAULT NULL,
  UPDATE_DATE datetime DEFAULT NULL,
  UPDATE_ID varchar(30) DEFAULT NULL,
  RES_REPLY_DATE datetime DEFAULT NULL,
  ADMIN_REPLY_DATE datetime DEFAULT NULL,
  ADMIN_PROCESS_GUBUN char(20) DEFAULT NULL,
  ADMIN_CANCELCODE char(20) DEFAULT NULL,
  USE_YN char(1) DEFAULT NULL,
  RES_TITLE varchar(100) DEFAULT NULL,
  RES_PASSWORD varchar(255) DEFAULT NULL,
  MEETING_SEQ varchar(100) DEFAULT NULL,
  RES_ATTENDLIST varchar(1000) DEFAULT NULL,
  MEETINGLOG text DEFAULT NULL,
  RES_FILE1 varchar(20) DEFAULT NULL,
  RES_FILE2 varchar(20) DEFAULT NULL,
  CONFERENCE_ID varchar(10) DEFAULT NULL,
  CON_NUMBER varchar(10) DEFAULT NULL,
  CON_PIN varchar(8) DEFAULT NULL,
  CON_VIRTUAL_PIN varchar(8) DEFAULT NULL,
  CON_ALLOWSTREAM varchar(10) DEFAULT NULL,
  CON_BLACKDIAL varchar(10) DEFAULT NULL,
  CON_SENDNOTI varchar(10) DEFAULT NULL,
  RES_SEND_RESULT varchar(20) DEFAULT NULL,
  RES_SEND_RESULT_TXT varchar(100) DEFAULT NULL,
  RES_EQUPINFO varchar(1000) DEFAULT NULL
) ;




CREATE TABLE TB_SWCTIME (
  TIME_SEQ int(11) NOT NULL IDENTITY(1,1) primary key ,
  CENTER_ID char(9)  not null ,
  SWC_RESDAY char(8)  not null ,
  SWC_TIME varchar(4) DEFAULT NULL,
  RES_SEQ int(11) DEFAULT NULL,
  APPRIVAL char(1) DEFAULT NULL,
  USE_YN char(1) DEFAULT NULL,
  ITME_ID varchar(20) not null
) ;
